---
name: test-and-build
on:
  push:
    branches: ['*']
    tags: ['v*']

permissions:
  contents: write

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/gh-arch-env@sha256:5db95c48e7aa828d079439daba6fd0d033ca31376818d4aad29eea46f9945b3a
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/vault-user-token/vault-user-token

      - name: Build release
        run: make publish
        env:
          FORCE_SKIP_UPLOAD: 'true'
          MOD_MODE: readonly
          NO_TESTS: 'true'
          PACKAGES: '.'

      - name: Extract changelog
        run: 'awk "/^#/ && ++c==2{exit}; /^#/f" "History.md" | tail -n +2 >release_changelog.md'

      - name: Release
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1.18.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: '.build/*'
          bodyFile: release_changelog.md
          draft: false
          generateReleaseNotes: false
